version: '3'

vars:
  REPO_DIR: ~/code/tasks

tasks:
  edit:
    desc: Edit the Taskfile.yaml in vscode
    dir: '{{.REPO_DIR}}'
    cmds:
      - code Taskfile.yaml

  readme:
    desc: Edit the README.md in vscode
    dir: '{{.REPO_DIR}}'
    cmds:
      - code README.md

  push:
    desc: git commit and push changes to Taskfile.yaml and README.md
    dir: '{{.REPO_DIR}}'
    cmds:
      - git add README.md
      - git add Taskfile.yaml
      - git add tasks.yaml
      - git commit -m "latest changes"
      - git push

  uds-clean:
    desc: Delete all .zst files from <pwd> and <pwd>/bundle
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - find . -name "*.zst" | xargs rm 

  lint:
    desc: lint yaml
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - uds run lint:all

  chbs:
    desc: Correct Horse Battery Staple
    dir: /home/eric/code/psychic-happiness/chbs
    cmds:
      - shuf -n 2 words.txt

  jwt:
    desc: "Decode a JWT token"
    dir: /home/eric/code/psychic-happiness/scripts
    cmds:
      - echo "Args {{.CLI_ARGS}}"

  doug:
    desc: Doug
    dir: '{{.REPO_DIR}}'  
    cmds:
      - uds run setup:create-doug-user --set KEYCLOAK_GROUP="/UDS Core/Admin"

  keycloak:
    desc: Keycloak Admin Password
    dir: '{{.REPO_DIR}}' 
    cmds:
      - uds run setup:print-keycloak-admin-password

  uuid:
    desc: Generate a UUID and copy to clipboard
    cmds:
      - uuidgen | tr '[:upper:]' '[:lower:]' | tr -d '\n' | pbcopy

  colima-setup:
    desc: blow away colima and start over
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - colima delete uds -f
      - colima start --cpu 8 --memory 28 --disk 50 --vm-type vz  --vz-rosetta --arch aarch64 --profile uds

      - colima ssh --profile uds 'sudo sysctl -w vm.max_map_count=524288'
      - colima ssh --profile uds 'sudo sysctl -w fs.file-max=131072'

      - echo "*** Done! Now run the commands below ***"
      - echo "colima ssh --profile uds"
      - echo "sudo sysctl -w vm.max_map_count=524288"
      - echo "sudo sysctl -w fs.file-max=131072"
